#!/usr/bin/env python3
"""Fail when an exact direct requirement is absent or stale in its lock."""

from __future__ import annotations

from pathlib import Path
import re
import sys


PIN = re.compile(r"([A-Za-z0-9_.-]+)(?:\[[A-Za-z0-9_,.-]+\])?==([^\s;\\]+)")
LOCK_HEADER = (
    "# This file was autogenerated by uv 0.11.31 via the following command:\n"
    "#    uvx --from uv==0.11.31 uv pip compile requirements.txt "
    "--python-version 3.14 --python-platform linux --generate-hashes "
    "--output-file requirements.lock\n"
)


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def parse_direct(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        requirement = raw.split("#", 1)[0].strip()
        if not requirement:
            continue
        match = PIN.fullmatch(requirement)
        if match is None:
            raise SystemExit(f"{path}: direct dependency is not exact-pinned: {requirement}")
        pins[canonical_name(match.group(1))] = match.group(2)
    if not pins:
        raise SystemExit(f"{path}: no direct dependency pins found")
    return pins


def parse_lock(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith(LOCK_HEADER):
        raise SystemExit(f"{path}: lock was not generated with the reviewed uv version")
    pins: dict[str, str] = {}
    for raw in text.splitlines():
        match = PIN.match(raw)
        if match is None:
            continue
        name = canonical_name(match.group(1))
        if name in pins:
            raise SystemExit(f"{path}: duplicate locked dependency: {name}")
        pins[name] = match.group(2)
    if not pins:
        raise SystemExit(f"{path}: no locked dependencies found")
    return pins


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: validate-python-locks.py REQUIREMENTS LOCK")
    direct_path, lock_path = map(Path, sys.argv[1:])
    direct = parse_direct(direct_path)
    locked = parse_lock(lock_path)
    stale = {
        name: (version, locked.get(name))
        for name, version in direct.items()
        if locked.get(name) != version
    }
    if stale:
        details = ", ".join(
            f"{name}=={expected} (lock={actual or 'missing'})"
            for name, (expected, actual) in sorted(stale.items())
        )
        raise SystemExit(f"{lock_path}: regenerate from {direct_path}: {details}")


if __name__ == "__main__":
    main()
